import { Header } from "@/components/layout/header"
import { Footer } from "@/components/layout/footer"

export const metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Software Defined Factory. Please read these terms carefully before using our website and services.",
}

export default function TermsOfServicePage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />

      <main className="flex-1">
        <article className="container mx-auto max-w-4xl px-4 py-24">
          <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
          <p className="text-muted-foreground mb-12">Last updated: 12 February 2026</p>

          <div className="prose prose-lg dark:prose-invert max-w-none">
            <h2>1. Agreement to Terms</h2>
            <p>
              By accessing or using the Software Defined Factory website at{" "}
              <strong>softwaredefinedfactory.com</strong> (the &ldquo;Site&rdquo;), you agree to be bound by
              these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, you must not
              use the Site.
            </p>
            <p>
              We reserve the right to update these Terms at any time. Changes will be effective when posted on
              this page. Your continued use of the Site after changes are posted constitutes your acceptance of
              the revised Terms.
            </p>

            <h2>2. Description of Services</h2>
            <p>Software Defined Factory provides:</p>
            <ul>
              <li>Educational content about smart manufacturing, Industry 4.0, and IIoT (blog articles)</li>
              <li>Online courses and learning materials (some free, some paid)</li>
              <li>Free interactive tools and calculators (e.g. ROI Calculator, OEE Calculator)</li>
              <li>A newsletter with industry insights and updates</li>
            </ul>

            <h2>3. User Accounts</h2>

            <h3>Account Creation</h3>
            <p>
              To access certain features of the Site (such as courses and your dashboard), you must create an
              account. You agree to:
            </p>
            <ul>
              <li>Provide accurate and complete information during registration</li>
              <li>Keep your login credentials confidential</li>
              <li>Notify us immediately of any unauthorised use of your account</li>
              <li>Accept responsibility for all activity that occurs under your account</li>
            </ul>

            <h3>Account Termination</h3>
            <p>
              We may suspend or terminate your account at our discretion if you violate these Terms or engage
              in conduct that we deem harmful to the Site, other users, or our business. You may delete your
              account at any time by contacting us.
            </p>

            <h2>4. Courses and Purchases</h2>

            <h3>Pricing</h3>
            <p>
              Course prices are displayed on the Site and are subject to change. Any price changes will not
              affect courses you have already purchased.
            </p>

            <h3>Payment</h3>
            <p>
              Payments are processed securely via Stripe. By making a purchase, you agree to Stripe&apos;s
              terms of service. You represent that you are authorised to use the payment method provided.
            </p>

            <h3>Access</h3>
            <p>
              Upon purchasing a course, you receive a personal, non-transferable licence to access and view the
              course content for as long as the course remains available on the Site. You do not acquire
              ownership of the course content.
            </p>

            <h3>Refunds</h3>
            <p>
              We offer a 30-day money-back guarantee on all paid courses. If you are unsatisfied with a course,
              contact us within 30 days of purchase for a full refund. Refunds will be processed to the original
              payment method.
            </p>

            <h2>5. Free Tools and Calculators</h2>
            <p>
              Our free tools (such as the ROI Calculator) are provided &ldquo;as is&rdquo; for informational and
              educational purposes only. Results generated by these tools are estimates and should not be relied
              upon as professional financial, engineering, or business advice. We make no guarantees regarding
              the accuracy, completeness, or applicability of tool outputs to your specific situation.
            </p>

            <h2>6. Intellectual Property</h2>

            <h3>Our Content</h3>
            <p>
              All content on the Site — including text, images, videos, graphics, logos, course materials, tools,
              and software — is owned by Software Defined Factory or its licensors and is protected by copyright,
              trademark, and other intellectual property laws.
            </p>

            <h3>Permitted Use</h3>
            <p>You may:</p>
            <ul>
              <li>View and access content for personal, non-commercial learning purposes</li>
              <li>Share links to blog posts and public pages</li>
              <li>Print or save blog articles for your personal reference</li>
            </ul>

            <h3>Prohibited Use</h3>
            <p>You may not:</p>
            <ul>
              <li>Reproduce, distribute, or publicly display course content</li>
              <li>Share your course access credentials with others</li>
              <li>Download, rip, or copy course videos</li>
              <li>Use our content to create competing products or services</li>
              <li>Remove any copyright or proprietary notices from our content</li>
              <li>Use automated tools to scrape or extract content from the Site</li>
            </ul>

            <h2>7. User Conduct</h2>
            <p>When using the Site, you agree not to:</p>
            <ul>
              <li>Violate any applicable laws or regulations</li>
              <li>Impersonate another person or entity</li>
              <li>Interfere with or disrupt the Site or its servers</li>
              <li>Attempt to gain unauthorised access to any part of the Site</li>
              <li>Upload malicious code, viruses, or harmful content</li>
              <li>Harass, abuse, or harm other users</li>
              <li>Use the Site for any unlawful or fraudulent purpose</li>
            </ul>

            <h2>8. Newsletter and Communications</h2>
            <p>
              By subscribing to our newsletter, you consent to receive periodic emails with educational content,
              product updates, and promotional offers. You can unsubscribe at any time by clicking the
              &ldquo;unsubscribe&rdquo; link in any email. We will not sell or share your email address with
              third parties for their own marketing purposes.
            </p>

            <h2>9. Disclaimer of Warranties</h2>
            <p>
              The Site and its content are provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
              warranties of any kind, either express or implied. We do not warrant that:
            </p>
            <ul>
              <li>The Site will be uninterrupted, error-free, or secure</li>
              <li>Content will be accurate, complete, or current</li>
              <li>Any particular results will be achieved from using the Site or courses</li>
              <li>Defects will be corrected in a timely manner</li>
            </ul>
            <p>
              Educational content and tools are provided for informational purposes. They do not constitute
              professional advice. You should consult qualified professionals for decisions about manufacturing
              operations, investments, or business strategy.
            </p>

            <h2>10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Software Defined Factory and its owners, employees, and
              affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive
              damages, including but not limited to loss of profits, data, or business opportunities, arising
              from your use of the Site.
            </p>
            <p>
              Our total liability to you for any claims arising from your use of the Site shall not exceed the
              amount you paid to us in the twelve (12) months preceding the claim.
            </p>

            <h2>11. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Software Defined Factory from any claims, losses,
              damages, liabilities, and expenses (including legal fees) arising from your use of the Site,
              violation of these Terms, or infringement of any third-party rights.
            </p>

            <h2>12. Third-Party Links</h2>
            <p>
              The Site may contain links to third-party websites or services. We are not responsible for the
              content, privacy practices, or availability of these external sites. Accessing third-party links
              is at your own risk.
            </p>

            <h2>13. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of Ireland, without
              regard to conflict of law principles. Any disputes arising from these Terms or your use of the
              Site shall be subject to the exclusive jurisdiction of the courts of Ireland.
            </p>

            <h2>14. Severability</h2>
            <p>
              If any provision of these Terms is found to be unenforceable or invalid, that provision shall be
              limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain
              in full force and effect.
            </p>

            <h2>15. Entire Agreement</h2>
            <p>
              These Terms, together with our Privacy Policy, constitute the entire agreement between you and
              Software Defined Factory regarding your use of the Site and supersede any prior agreements.
            </p>

            <h2>16. Contact Us</h2>
            <p>
              If you have questions about these Terms, please contact us at:
            </p>
            <p>
              <strong>Email:</strong> legal@softwaredefinedfactory.com
            </p>
          </div>
        </article>
      </main>

      <Footer />
    </div>
  )
}
